version: '3.8'

services:
  # --- Service Base de données ---
  db:
    image: postgres:15
    container_name: pg-tickets-docker
    environment:
      POSTGRES_DB: codingtickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Le script init.sql sera exécuté automatiquement au premier démarrage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- Service Application Tomcat ---
  app:
    build: . # Construit l'image depuis le Dockerfile courant
    container_name: app-tickets-tomcat
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/codingtickets
      DB_USER: postgres
      DB_PASSWORD: postgres
volumes:
  pgdata: